#version: '3.9'

services:
  jackie-shop-service:
    container_name: JackieShop
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8085:8085'
    depends_on:
      - postgres-db
    networks:
      - backend-2
    restart: on-failure

  postgres-db:
    container_name: jackie-shop-postgres-db
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-2
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgresdb" ]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  postgres-data:

networks:
  backend-2:
    driver: bridge


