server:
  port: ${SERVER_PORT:8085}
  address: ${SERVER_ADDRESS:0.0.0.0}
#  servlet:
#    context-path: /api


spring:
  application:
    name: ecommerce-web
  profiles:
    active: dev

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      password:  # Set your Redis password here if required
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1
      timeout: 2000
      database: 0
      connect-timeout: 2000




logging:
  level:
    root: INFO
    web: OFF
    org.springframework: INFO
    org.apache: OFF
    kafka: OFF


