spring:
  config:
    activate:
      on-profile: dev

  devtools:
    livereload:
      enabled: true

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 8
      driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# env
image:
  base:
    url: ${IMAGE_BASE_URL}

firebase:
  service-account-path: ${FIREBASE_SERVICE_ACCOUNT_PATH}
  storage-bucket: ${FIREBASE_STORAGE_BUCKET}

jwt:
  signer-key: ${JWT_SIGNER_KEY}

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}

stripe:
  api: ${API_STRIPE_KEY}
  webhook: ${API_STRIPE_WEBHOOK_KEY}

