server:
  port: ${SERVER_PORT}
#  servlet:
#    context-path: /api
spring:
  profiles:
    include: dotenv
  config:
    name: application.yml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

  #  postgresql
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 8
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

image:
  base:
    url: ${IMAGE_BASE_URL}

firebase:
  service-account-path: ${FIREBASE_SERVICE_ACCOUNT_PATH}
  storage-bucket: ${FIREBASE_STORAGE_BUCKET}

