server:
  port: ${SERVER_PORT:8085}
  address: ${SERVER_ADDRESS:localhost}
#  servlet:
#    context-path: /api


spring:
  application:
    name: ecommerce-web
  profiles:
    active: dev

logging:
  level:
    root: INFO
    web: OFF
    org.springframework: INFO
    org.apache: OFF
    kafka: OFF


