spring:
  config:
    activate:
      on-profile: dev

  devtools:
    livereload:
      enabled: true

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/jackie_shop} #mandatory
    username: ${DATABASE_USERNAME:postgres} #mandatory
    password: ${DATABASE_PASSWORD:nhatcoi123} #mandatory
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 8
      driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# env
image:
  base:
    url: ${IMAGE_BASE_URL:IMAGE_BASE_URL}

firebase:
  service-account-path: /app/config/ecommerce-web-key.json
  storage-bucket: ${FIREBASE_STORAGE_BUCKET:FIREBASE_STORAGE_BUCKET}

jwt:
  signer-key: ${JWT_SIGNER_KEY:JWT_SIGNER_KEY}

stripe:
  api: ${API_STRIPE_KEY:API_STRIPE_KEY}
  webhook: ${API_STRIPE_WEBHOOK_KEY:API_STRIPE_WEBHOOK_KEY}

## All Key for dev-test