name: Deploy BE to VPS

on:
  push:
    paths:
      - '**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t ecommerce-be .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag ecommerce-be ${{ secrets.DOCKER_USERNAME }}/ecommerce-be:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-be:latest

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            echo ">>> Pulling latest Docker image"
            docker pull ${{ secrets.DOCKER_USERNAME }}/ecommerce-be:latest
            
            echo ">>> Stopping & removing old container"
            docker stop ecommerce-be || true
            docker rm ecommerce-be || true
            
            echo ">>> Running new container with .env file"
            docker run -d \
              --name ecommerce-be \
              --env-file /home/jackie/ENV/ecommerce-be/.env \
              -v /home/jackie/ENV/ecommerce-be/ecommerce-web-key.json:/app/config/ecommerce-web-key.json \
              -p 8085:8085 \
              ${{ secrets.DOCKER_USERNAME }}/ecommerce-be:latest
